APP = ensemble
SOURCES = ensemble/ensemble.c \
          ensemble/ensemble_common/voja.c \
          ensemble/ensemble_common/pes.c \
          ensemble/ensemble_common/neuron_lif.c \
          ensemble/ensemble_common/filtered_activity.c \
          ensemble/ensemble_common/encoder_recording.c \
          ensemble/ensemble_common/recording.c

CFLAGS += -I $(MODIFIED_DIR)/common/
include ../nengo_support.mk